### ISSUE TITLE
Trying to get property of non-object

### ISSUE THREAD

**Issue by isanai69** [ronanflavio/easychat_l5#1]
in EasychatController.php line 344
at HandleExceptions->handleError('8', 'Trying to get property of non-object', 'C:\xampp\htdocs\social\vendor\ronanflavio\easychatl5\src\Http\EasychatController.php', '344', array('query' => object(Builder), 'server_messages' => array('model' => 'Ronanflavio\Easychat\Models\ServerMessage', 'table' => 'ec_server_messages', 'id' => 'id', 'sent_by' => 'sent_by', 'sent_to' => 'sent_to', 'room_id' => 'room_id', 'text' => 'text', 'col_size' => 'col_size', 'created_at' => 'created_at', 'updated_at' => 'updated_at'), 'user' => array('model' => 'App\User', 'table' => 'users', 'id' => 'id', 'name' => 'name', 'created_at' => 'created_at', 'updated_at' => 'updated_at'))) in EasychatController.php line 344

Having this error code on a fresh install publish and migrate 
Hope u can give me a solution because i need this package 
Thank you

**Comment by ronanflavio** [comment]
Hello there.
If you correctly configured the users table's data into `config/packages/Ronanflavio/Easychat/tables.php` file after publish it, probably the error occurrs because you're not logged in with any user into the application.
Try to create an user in your users' table (if you didn't it yet) and put the snippet bellow before all your routes into the `app/Http/routes.php` file:
`\Auth::loginUsingId(1);`
Where the 1 is the user's ID at your users' table. Feel free to change it if necessary.
If it doesn't work, please, tell me to find the way.
Regards.

**Comment by isanai69** [comment]
Hello and sorry for bothering you.
I created a user and logged and when i go to the url localhost/social/public/easychat
still the error shows
Thank you for the fast reply..

**Comment by isanai69** [comment]
I also changed some field in the config table.php for the table and namefields

**Comment by ronanflavio** [comment]
But the problem has still happening?
If yes, could you show me your `config/packages/Ronanflavio/Easychat/tables.php` file and your users' table structure, please? Cause in that line where the error occurs, the package tries to get the `id` from authenticated user, so I can't see other possibility. Maybe there are something wrong in the map at tables.php file, or you're not using the Laravel Auth to authenticate. Could it be possible?

**Comment by isanai69** [comment]
Hello This is the full view of the error

in EasychatController.php line 343
at HandleExceptions->handleError('8', 'Trying to get property of non-object', 'C:\xampp\htdocs\chat\vendor\ronanflavio\easychatl5\src\Http\EasychatController.php', '343', array('query' => object(Builder), 'server_messages' => array('model' => 'Ronanflavio\Easychat\Models\ServerMessage', 'table' => 'ec_server_messages', 'id' => 'id', 'sent_by' => 'sent_by', 'sent_to' => 'sent_to', 'room_id' => 'room_id', 'text' => 'text', 'col_size' => 'col_size', 'created_at' => 'created_at', 'updated_at' => 'updated_at'), 'user' => array('model' => 'App\User', 'table' => 'users', 'id' => 'id', 'name' => 'name', 'created_at' => 'created_at', 'updated_at' => 'updated_at'))) in EasychatController.php line 343
at EasychatController->Ronanflavio\Easychat\Http{closure}(object(Builder))
at call_user_func(object(Closure), object(Builder)) in Builder.php line 729
at Builder->where(object(Closure)) in EasychatController.php line 345
at EasychatController->usersList(object(EasychatRequest)) in EasychatController.php line 52
at EasychatController->getIndex()
at call_user_func_array(array(object(EasychatController), 'getIndex'), array()) in Controller.php line 80
at Controller->callAction('getIndex', array()) in ControllerDispatcher.php line 146
at ControllerDispatcher->call(object(EasychatController), object(Route), 'getIndex') in ControllerDispatcher.php line 94
at ControllerDispatcher->Illuminate\Routing{closure}(object(Request))
at call_user_func(object(Closure), object(Request)) in Pipeline.php line 52
at Pipeline->Illuminate\Routing{closure}(object(Request))
at call_user_func(object(Closure), object(Request)) in Pipeline.php line 102
at Pipeline->then(object(Closure)) in ControllerDispatcher.php line 96
at ControllerDispatcher->callWithinStack(object(EasychatController), object(Route), object(Request), 'getIndex') in ControllerDispatcher.php line 54
at ControllerDispatcher->dispatch(object(Route), object(Request), 'Ronanflavio\Easychat\Http\EasychatController', 'getIndex') in Route.php line 174
at Route->runController(object(Request)) in Route.php line 140
at Route->run(object(Request)) in Router.php line 724
at Router->Illuminate\Routing{closure}(object(Request))
at call_user_func(object(Closure), object(Request)) in Pipeline.php line 52
at Pipeline->Illuminate\Routing{closure}(object(Request))
at call_user_func(object(Closure), object(Request)) in Pipeline.php line 102
at Pipeline->then(object(Closure)) in Router.php line 726
at Router->runRouteWithinStack(object(Route), object(Request)) in Router.php line 699
at Router->dispatchToRoute(object(Request)) in Router.php line 675
at Router->dispatch(object(Request)) in Kernel.php line 246
at Kernel->Illuminate\Foundation\Http{closure}(object(Request))
at call_user_func(object(Closure), object(Request)) in Pipeline.php line 52
at Pipeline->Illuminate\Routing{closure}(object(Request)) in CheckForMaintenanceMode.php line 44
at CheckForMaintenanceMode->handle(object(Request), object(Closure))
at call_user_func_array(array(object(CheckForMaintenanceMode), 'handle'), array(object(Request), object(Closure))) in Pipeline.php line 136
at Pipeline->Illuminate\Pipeline{closure}(object(Request))
at call_user_func(object(Closure), object(Request)) in Pipeline.php line 32
at Pipeline->Illuminate\Routing{closure}(object(Request))
at call_user_func(object(Closure), object(Request)) in Pipeline.php line 102
at Pipeline->then(object(Closure)) in Kernel.php line 132
at Kernel->sendRequestThroughRouter(object(Request)) in Kernel.php line 99
at Kernel->handle(object(Request)) in index.php line 53

This is the Map for config/packages/Ronanflavio/Easychat/tables.php:
(nothing Chaged so far becasue i added the photo)
` <?php

return array(

```
/*
|--------------------------------------------------------------------------
| Users table
|--------------------------------------------------------------------------
|
| Below you will set the model, table and fields names from users table.
|
*/

'users' => array(

    /**
     * Set the Model name:
     */

    'model' => 'App\User',

    /**
     * Set the Table name:
     */

    'table' => 'users',

    /**
     * Set the Fields names:
     */

    'id'         => 'id',
    'name'       => 'name',
    'photo'      => null,
    'created_at' => 'created_at',
    'updated_at' => 'updated_at',
),

/*
|--------------------------------------------------------------------------
| Users Messages table
|--------------------------------------------------------------------------
|
| Below you will set the model, table and fields names from user messages
| table.
|
*/

'user_messages' => array(

    /**
     * Set the Model name:
     */

    'model' => 'Ronanflavio\Easychat\Models\UserMessage',

    /**
     * Set the Table name:
     */

    'table' => 'ec_user_messages',

    /**
     * Set the Fields names:
     */

    'id'                => 'id',
    'user_id'           => 'user_id',
    'sent_by'           => 'sent_by',
    'sent_to'           => 'sent_to',
    'server_message_id' => 'server_message_id',
    'created_at'        => 'created_at',
    'updated_at'        => 'updated_at',
),

/*
|--------------------------------------------------------------------------
| Server Messages table
|--------------------------------------------------------------------------
|
| Below you will set the model, table and fields names from rooms table.
|
*/

'server_messages' => array(

    /**
     * Set the Model name:
     */

    'model' => 'Ronanflavio\Easychat\Models\ServerMessage',

    /**
     * Set the Table name:
     */

    'table' => 'ec_server_messages',

    /**
     * Set the Fields names:
     */

    'id' => 'id',
    'sent_by' => 'sent_by',
    'sent_to' => 'sent_to',
    'room_id' => 'room_id',
    'text' => 'text',
    'col_size' => 'col_size',
    'created_at' => 'created_at',
    'updated_at' => 'updated_at',
),

/*
|--------------------------------------------------------------------------
| Rooms table
|--------------------------------------------------------------------------
|
| Below you will set the model, table and fields names from rooms table.
|
*/

'rooms' => array(

    /**
     * Set the Model name:
     */

    'model' => 'Ronanflavio\Easychat\Models\Room',

    /**
     * Set the Table name:
     */

    'table' => 'ec_rooms',

    /**
     * Set the Fields names:
     */

    'id' => 'id',
    'user_a' => 'user_a',
    'user_b' => 'user_b',
    'created_at' => 'created_at',
    'updated_at' => 'updated_at',
),
```

); `

My table structure for users:
![users_table](https://cloud.githubusercontent.com/assets/16869392/14750222/3fb5cfae-08f6-11e6-81fe-df958b539fdb.png)

And lastly im using the Auth scafold for laravel 5.2

Thank you in advance

**Comment by ronanflavio** [comment]
Ok, I saw here. It looks fine. Have you putted the code ( `\Auth::loginUsingId(1);` ) at the top of your `app/Http/routes.php` to manually login an user by id into the application?
If you didn't, try it and tell me what happened. It's because I can't see other way to figure it out...
I've created a new fresh application in Laravel 5.2 today with the package and setting out all the configurations. But when I've tried to access `http://myhost.local/easychat` without to login, I faced the same error. So, once I've logged in manually, it was ok.

**Comment by isanai69** [comment]
Weird tried using the manual login then another error arises
Array to string conversion - same Line,
Did another fresh install

**Comment by ronanflavio** [comment]
Sorry for the delay.
Could you put the snippet bellow into your `app\Http\routes.php` file? Do it at the top of all your routes.

```
dd(\Auth::loginUsingId(1));
```

Please, access your easychat URL and place here what is showed in the object.

**Comment by isanai69** [comment]
here it sir..

User {#120 ▼
  #table: "users"
  #fillable: array:3 [▼
    0 => "name"
    1 => "email"
    2 => "password"
  ]
  #hidden: array:2 [▼
    0 => "password"
    1 => "remember_token"
  ]
  #connection: null
  #primaryKey: "id"
  #perPage: 15
  +incrementing: true
  +timestamps: true
  #attributes: array:8 [▼
    "id" => 1
    "name" => "nico"
    "email" => "nico@gmail.com"
    "password" => "$2y$10$19EVtRG3Ea8K4gR/aUmXbeu3g4x.FEd9OxC4BrSvPEndmFKel5PqK"
    "photo" => null
    "remember_token" => "LytyOtBcDs8nVTFFycfGozEBA6x8Ae7u8c7hSfgZ3dQDN1SIsGg0hNutFe4c"
    "created_at" => "2016-04-22 06:58:14"
    "updated_at" => "2016-04-22 18:28:46"
  ]
  #original: array:8 [▼
    "id" => 1
    "name" => "nico"
    "email" => "nico@gmail.com"
    "password" => "$2y$10$19EVtRG3Ea8K4gR/aUmXbeu3g4x.FEd9OxC4BrSvPEndmFKel5PqK"
    "photo" => null
    "remember_token" => "LytyOtBcDs8nVTFFycfGozEBA6x8Ae7u8c7hSfgZ3dQDN1SIsGg0hNutFe4c"
    "created_at" => "2016-04-22 06:58:14"
    "updated_at" => "2016-04-22 18:28:46"
  ]
  #relations: []
  #visible: []
  #appends: []
  #guarded: array:1 [▼
    0 => "*"
  ]
  #dates: []
  #dateFormat: null
  #casts: []
  #touches: []
  #observables: []
  #with: []
  #morphClass: null
  +exists: true
  +wasRecentlyCreated: false
}

**Comment by ronanflavio** [comment]
Navigate to `vendor/ronanflavio/easychatl5/src/Http/EasychatController.php` file, go to line 328 and put this snippet bellow:

```
## previous code here ##
...
...
...
## PUT THIS CODE ##
        dd([
            $server_messages['table'],
            $server_messages['sent_to'],
            Auth::user()->$user['id']
            ]);
## END OF VAR DUMP ##
...
...
...
## the code continues ##
```

And then, show me what came. =D

**Comment by isanai69** [comment]
i'm sorry i put the code but its not showing the dd its still the error. 
and still thank you for helping me. T_T

**Comment by ronanflavio** [comment]
Don't worry, haha. Let's try to understand that. =D

Have you published the vendor's folder? The command is:

```
php artisan vendor:publish
```

**Comment by isanai69** [comment]
ohh it seems the user cannot convert to string, I remove the Auth::user()->$user['id'] and
it shows:

array:2 [▼
  0 => "ec_server_messages"
  1 => "sent_to"
]

\Auth::loginUsingId(1); is still in the route.php

**Comment by isanai69** [comment]
i change the Auth::user($user['id'])
 dd([
            $server_messages['table'],
            $server_messages['sent_to'],
            Auth::user($user['id'])
            ]);

array:3 [▼
  0 => "ec_server_messages"
  1 => "sent_to"
  2 => User {#120 ▼
    #table: "users"
    #fillable: array:4 [▼
      0 => "name"
      1 => "email"
      2 => "password"
      3 => "photo"
    ]
    #hidden: array:2 [▼
      0 => "password"
      1 => "remember_token"
    ]
    #connection: null
    #primaryKey: "id"
    #perPage: 15
    +incrementing: true
    +timestamps: true
    #attributes: array:8 [▼
      "id" => 1
      "name" => "nico"
      "email" => "nico@gmail.com"
      "password" => "$2y$10$19EVtRG3Ea8K4gR/aUmXbeu3g4x.FEd9OxC4BrSvPEndmFKel5PqK"
      "photo" => null
      "remember_token" => "LytyOtBcDs8nVTFFycfGozEBA6x8Ae7u8c7hSfgZ3dQDN1SIsGg0hNutFe4c"
      "created_at" => "2016-04-22 06:58:14"
      "updated_at" => "2016-04-22 18:28:46"
    ]
    #original: array:8 [▼
      "id" => 1
      "name" => "nico"
      "email" => "nico@gmail.com"
      "password" => "$2y$10$19EVtRG3Ea8K4gR/aUmXbeu3g4x.FEd9OxC4BrSvPEndmFKel5PqK"
      "photo" => null
      "remember_token" => "LytyOtBcDs8nVTFFycfGozEBA6x8Ae7u8c7hSfgZ3dQDN1SIsGg0hNutFe4c"
      "created_at" => "2016-04-22 06:58:14"
      "updated_at" => "2016-04-22 18:28:46"
    ]
    #relations: []
    #visible: []
    #appends: []
    #guarded: array:1 [▼
      0 => "*"
    ]
    #dates: []
    #dateFormat: null
    #casts: []
    #touches: []
    #observables: []
    #with: []
    #morphClass: null
    +exists: true
    +wasRecentlyCreated: false
  }
]

**Comment by ronanflavio** [comment]
hmmm, I've seen that kind of problem before in PHP...
Try to envolve the `$user['id']` in braces. So, your dd code will look like this:

```
      dd([
            $server_messages['table'],
            $server_messages['sent_to'],
            Auth::user()->{$user['id']}
            ]);
```

**Comment by isanai69** [comment]
tried the code:
array:3 [▼
  0 => "ec_server_messages"
  1 => "sent_to"
  2 => 1
]

**Comment by ronanflavio** [comment]
Yes! That's the way. If I place the braces involving all variables that is called like this:
`something->$something` to `something->{$something}`, the problem will be solved.
Can you wait one more day? lol
And tell me, what is your PHP version?

**Comment by isanai69** [comment]
PHP 7.0.1 and laravel 5.2;

for the one working used the \Auth::loginUsingId(1);

and for the laravel php artisan make:auth 
it gives me
array:3 [▼
0 => "ec_server_messages"
1 => "sent_to"
2 => null
]
and Thank you so much for helping me and hope this will be implemented on my project.. having a chat feature. :))))) haha

**Comment by ronanflavio** [comment]
Haha, ok bro. The problem will be solved soon.
It's because I've made the package using PHP 5.6.4. The newest version maybe changed some rules with the variables.

**Comment by ronanflavio** [comment]
Hello there. Try to run this command and take a look if it's ok now.

```
composer require ronanflavio/easychatl5
```

**Comment by isanai69** [comment]
Hello
It works like charm!! haha 
but only with the \Auth::loginUsingId(1); T_T

the issue still arises when i used the authcontroller from the auth scaffold cannot get the current user->id;
well at least it works,

**Comment by ronanflavio** [comment]
I'll look to it soon sir, and you will be notified. =D
Thanks

**Comment by yazirrizki** [comment]
public function usersList(EasychatRequest $request, $param = null, $impersonate = true)
    {
        $input = $request->input();

        $user = $this->tables('users');
        $server_messages = $this->tables('server_messages');

        if (isset($input['all_users']))
        {
            return Response::json($user['model']::select(array(
                $user['name'].' as username',
                $user['id'].' as user_id'
            ))->lists('username', 'user_id'));
        }

        _$result = $user['model']::join($server_messages['table'], function($join) use ($user, $server_messages)
            {
                $join->on($server_messages['table'].'.'.$server_messages['sent_to'], '=', $user['table'].'.'.$user['id'])
                    ->orOn($server_messages['table'].'.'.$server_messages['sent_by'], '=', $user['table'].'.'.$user['id']);
            })
            ->where(function($query) use ($server_messages, $user)
            {
                $query->where($server_messages['table'].'.'.$server_messages['sent_to'], '=', Auth::user()->{$user['id']})
                    ->orWhere($server_messages['table'].'.'.$server_messages['sent_by'], '=', Auth::user()->{$user['id']});
            });

            if ($impersonate)
            {
                $result = $result->where($user['table'].'.'.$user['id'], '<>', Auth::user()->{$user['id']});
            }_

        if ($param == 'ajax')
        {
            return Response::json($result->select(array(
                    $user['table'].'.'.$user['name'].' as username',
                    $user['table'].'.'.$user['id'].' as user_id'
                ))->lists('username', 'user_id'));
        }

        return $result->select(array(
                $user['table'].'.*',
                DB::raw('MAX('.$server_messages['table'].'.'.$server_messages['created_at'].') AS maximum')
            ))
            ->groupBy($user['table'].'.'.$user['id'])
            ->orderBy('maximum', 'DESC')
            ->get();
    }

now how to fix it? :astonished:

**Comment by yazirrizki** [comment]
public function usersList(EasychatRequest $request, $param = null, $impersonate = true)
    {
        $input = $request->input();

        $user = $this->tables('users');
        $server_messages = $this->tables('server_messages');

        if (isset($input['all_users']))
        {
            return Response::json($user['model']::select(array(
                $user['name'].' as username',
                $user['id'].' as user_id'
            ))->lists('username', 'user_id'));
        }

        $result = $user['model']::join($server_messages['table'], function($join) use ($user, $server_messages)
            {
                $join->on($server_messages['table'].'.'.$server_messages['sent_to'], '=', $user['table'].'.'.$user['id'])
                    ->orOn($server_messages['table'].'.'.$server_messages['sent_by'], '=', $user['table'].'.'.$user['id']);
            })
            ->where(function($query) use ($server_messages, $user)
            {
                **$query->where($server_messages['table'].'.'.$server_messages['sent_to'], '=', Auth::user()->{$user['id']})
                    ->orWhere($server_messages['table'].'.'.$server_messages['sent_by'], '=', Auth::user()->{$user['id']});**
            });

            if ($impersonate)
            {
                $result = $result->where($user['table'].'.'.$user['id'], '<>', Auth::user()->{$user['id']});
            }

        if ($param == 'ajax')
        {
            return Response::json($result->select(array(
                    $user['table'].'.'.$user['name'].' as username',
                    $user['table'].'.'.$user['id'].' as user_id'
                ))->lists('username', 'user_id'));
        }

        return $result->select(array(
                $user['table'].'.*',
                DB::raw('MAX('.$server_messages['table'].'.'.$server_messages['created_at'].') AS maximum')
            ))
            ->groupBy($user['table'].'.'.$user['id'])
            ->orderBy('maximum', 'DESC')
            ->get();
    }

**Comment by ghost** [comment]
public function usersList(EasychatRequest $request, $param = null, $impersonate = true)
    {
        $input = $request->input();

```
    $user = $this->tables('users');
    $server_messages = $this->tables('server_messages');

    if (isset($input['all_users']))
    {
        return Response::json($user['model']::select(array(
            $user['name'].' as username',
            $user['id'].' as user_id'
        ))->lists('username', 'user_id'));
    }

    $result = $user['model']::join($server_messages['table'], function($join) use ($user, $server_messages)
        {
            $join->on($server_messages['table'].'.'.$server_messages['sent_to'], '=', $user['table'].'.'.$user['id'])
                ->orOn($server_messages['table'].'.'.$server_messages['sent_by'], '=', $user['table'].'.'.$user['id']);
        })
        ->where(function($query) use ($server_messages, $user)
        {
```
- [ ] $query->where($server_messages['table'].'.'.$server_messages['sent_to'], '=', Auth::user()->{$user['id']})
- [ ]                     ->orWhere($server_messages['table'].'.'.$server_messages['sent_by'], '=', Auth::user()->{$user['id']});
  
  ```
      });
  
      if ($impersonate)
      {
          $result = $result->where($user['table'].'.'.$user['id'], '<>', Auth::user()->{$user['id']});
      }
  
  if ($param == 'ajax')
  {
      return Response::json($result->select(array(
              $user['table'].'.'.$user['name'].' as username',
              $user['table'].'.'.$user['id'].' as user_id'
          ))->lists('username', 'user_id'));
  }
  
  return $result->select(array(
          $user['table'].'.*',
          DB::raw('MAX('.$server_messages['table'].'.'.$server_messages['created_at'].') AS maximum')
      ))
      ->groupBy($user['table'].'.'.$user['id'])
      ->orderBy('maximum', 'DESC')
      ->get();
  ```
  
  }

How to fix it? :astonished:

**Comment by ronanflavio** [comment]
Haha, I'm sorry, but I can't see what happened. What's wrong? :confused:

**Comment by ghost** [comment]
I find your bug, its the  Auth::user()->{$user['id']})

try to replace it, and I think u gonna solve it.

**Comment by ronanflavio** [comment]
Where? I didn't understand what is the point.

**Comment by ghost** [comment]
Like isanal, your package just works if I use \Auth::loginUsingId(1);
I need to integrate with Auth, and maybe the problem is the Auth it self, or maybe u can give me your demo? so I can learn from it

**Comment by watio** [comment]
Hello, 
I have the same problem. it works only if I use \Auth::loginUsingId(1);

**Comment by ronanflavio** [comment]
Hello people.
I'm trying to solve it.
Soon as possible I'll fix it. Sorry for the dealy.

**Comment by watio** [comment]
ok, tank a lot

**Comment by ronanflavio** [comment]
The problem was solved folks. Try to update the package with the line bellow and tell me if it's right.

```
composer require ronanflavio/easychatl5
```
