### ISSUE TITLE
Not real-time?

### ISSUE THREAD

**Issue by huyle2607** [ronanflavio/easychat_l5#2]
Is it a real-time chat cause I have to click on the user list to refresh the chat area to see the message?

**Comment by ronanflavio** [comment]
Hey, I didn't understand very well what is your doubt, but, yes, you must to click on the user at the left list to load his conversation in the right panel. However, if a new message was sent at the same conversation, you don't need to refresh the page, it will just arrive.
I hope your question had been answered.
