### ISSUE TITLE
 it works only if I use \Auth::loginUsingId(1);

### ISSUE THREAD

**Issue by watio** [ronanflavio/easychat_l5#3]
Hello, i would like to make tchat between users who are login. But it doesn't. it works  only if i log user manualy.
 Can you help me please ?

**Comment by ronanflavio** [comment]
Hello sir.
The problem was solved. Try to run this line in your terminal and tell me if it's right.

```
composer require ronanflavio/easychatl5
```

**Comment by watio** [comment]
ok,  it works. tank a lot.

**Comment by watio** [comment]
is it possible to make it work like real time tchat ?
